# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: My-Host

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Path'
    mavenDirectory: 'C:\Maven\apache-maven-3.8.6\'
    mavenSetM2Home: false
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: CopyFiles@2
  inputs:
    Contents: '**\target\*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'banking-api'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'